[SC-172] Refactor eksportu ocen na backendzie
ajablonsk1/systematic-chaos pull request #111
Opened 2022-08-15 19:49 UTC by ajablonsk1

2022-08-16 16:18 UTC, dmncp requested changes
Jest jeden problem, sprawdzę dalej jak naprawisz

2022-08-16 16:18 UTC, dmncp commented on api/src/main/java/com/example/api/service/activity/task/TaskService.java
> +                    .toList();
Zrobiłeś wszędzie `activityMap.getFileTasks()` (linie 103, 107, 111) przez co mamy taki response:
![image](https://user-images.githubusercontent.com/63460537/184928975-c1d4ef93-8f1f-4358-aa70-35764f496666.png)
Co jest oczywiście błędem

2022-08-16 20:20 UTC, ajablonsk1 commented on api/src/main/java/com/example/api/service/activity/task/TaskService.java
> +                    .toList();
Si, my bad

2022-08-17 06:12 UTC, ajablonsk1 commented
Naprawiłem tego, daj znać jak coś jeszcze znajdziesz

2022-08-17 15:20 UTC, dmncp requested changes
Trzeba jeszcze dodać linijkę z nazwami kolumn jak we wzorcowym pliku csv:
![image](https://user-images.githubusercontent.com/63460537/185178096-109799a1-162c-4ec2-8632-031fe6015a13.png)

https://systematic-chaos.atlassian.net/jira/software/projects/SC/boards/1?selectedIssue=SC-97

2022-08-17 16:27 UTC, dmncp approved these changes

2022-08-17 16:41 UTC, merged