[SC-203] Back nie działa
ajablonsk1/systematic-chaos pull request #131
Opened 2022-08-23 14:07 UTC by ajablonsk1

2022-08-23 16:22 UTC, kwdrt commented
Na pewno jest źle na endpoincie /file - powinien zwracać z pustymi (null) polami remarks i points kiedy nie ma feedbacku zamiast komunikatu błędu

![chrome_B6pEJTV19d](https://user-images.githubusercontent.com/56168780/186213261-063b7587-a35d-4027-b2ca-7c18ee3ac660.png)

![obraz](https://user-images.githubusercontent.com/56168780/186213318-fa4bd4a9-fe72-4c35-970f-2e96e5575b56.png)

2022-08-23 16:26 UTC, kwdrt commented
/statistics też nie działa:
`error_message: "Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()\" because the return value of "com.example.api.dto.response.activity.task.result.TaskPointsStatisticsResponse.getDateMillis()\" is null"
`

musiał wylecieć jakiś null check, i/lub nie jest zapisywana data na backu dla aktywności

2022-08-23 16:27 UTC, dmncp commented
@kwdrt Podrzuć Adiemu screeny z toasta, może mu to rozjaśni bardziej ;)

2022-08-23 16:31 UTC, kwdrt commented
i /points/all/list ma to samo:
`Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "com.example.api.dto.response.activity.task.result.PointsResponse.getDateMillis()" is null`

> /statistics też nie działa: `error_message: "Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()\" because the return value of "com.example.api.dto.response.activity.task.result.TaskPointsStatisticsResponse.getDateMillis()\" is null" `
> 
> musiał wylecieć jakiś null check, i/lub nie jest zapisywana data na backu dla aktywności

2022-08-23 16:36 UTC, kwdrt requested changes
muszę zostawić komentarz, bo github nie daje inaczej

toasty o ktorych mówił @dmncp powielają error_message więc zamiast tego przekleiłem ich wartości tam gdzie istotne

2022-08-23 17:35 UTC, barto14753 commented
<img width="658" alt="Zrzut ekranu 2022-08-23 o 19 35 15" src="https://user-images.githubusercontent.com/56938330/186226600-86c74b43-02e4-404c-bfcc-3d5e3910732f.png">

2022-08-23 18:41 UTC, kwdrt approved these changes
Sprawdziłem znowu - wygląda że wszystko działa 👍

2022-08-23 18:50 UTC, barto14753 commented
<img width="553" alt="Zrzut ekranu 2022-08-23 o 20 49 15" src="https://user-images.githubusercontent.com/56938330/186239626-b4bcb160-3b21-4057-ad59-9a8760a67304.png">

Teraz /statistics bierze pod uwagę tylko ocenione fileTaskResult i fileTaskResult ma zapisywany czas oddania

2022-08-23 18:53 UTC, kwdrt requested changes
Cofam to, zapomniałem dodać ręcznie xd

Daj znać jak wszystkie poprawki przejdą

2022-08-23 18:59 UTC, barto14753 commented
<img width="791" alt="Zrzut ekranu 2022-08-23 o 20 58 42" src="https://user-images.githubusercontent.com/56938330/186241395-a4fcb36e-e9d9-4b56-bc20-aa5ba2ccb967.png">
/points/all/list też wydaje się działać (znowu setupowałem przez front)

2022-08-23 21:20 UTC, barto14753 commented
@kwdrt Wydaje mi się, że problemy, które zgłosiłeś są naprawione (ale lepiej sprawdź jeszcze raz dla pewności). Podczas rozwiązywania zadań, oceny itd. po froncie nie zauważyłem innych błędów

2022-08-24 06:05 UTC, ajablonsk1 commented
Dzięki za pomoc chłopaki

2022-08-24 15:40 UTC, kwdrt commented
👍 👍 
Wszystko sprawdziłem i działa, dobra robota

2022-08-24 15:40 UTC, kwdrt approved these changes

2022-08-24 15:42 UTC, merged