Sc 213 dodanie biblioteki react awesome reveal
ajablonsk1/systematic-chaos pull request #146
Opened 2022-08-29 16:48 UTC by kwdrt

Dodana biblioteka `react-awesome-reveal` z dwoma przykładami użycia - na ekranie odznak, i na ekranie wysyłania aktywności

2022-08-30 16:21 UTC, dmncp commented
![image](https://user-images.githubusercontent.com/63460537/187489088-bf52c429-bf72-4ed7-bf51-d0c73ff21aad.png)
Dopóki ten error nie zniknie nie ma szans na approve

2022-08-30 16:23 UTC, dmncp commented
Dorzuć do depsów w package.json:
    "@emotion/react": "^11.10.4",

2022-08-30 16:26 UTC, dmncp requested changes
Ten error musisz jakoś ogarnąć, nie może zostać :/

2022-08-30 16:57 UTC, kwdrt commented
Zrobiłem pewne zmiany, ale na node 14.0 - rzuć okiem czy teraz działa, dałem dependency takie samo jak ma wylistowana libka do animacji w package.json swoim

Przez przypadek zrobiłem wrap animacji na listę elementów i pakowało je w środku do `<></>` z className, a tak nie można... to znaczy można, ale są warningi - teraz powinno być naprawione.

2022-08-31 18:55 UTC, dmncp commented
Teraz niestety rzuca błąd w rangach:
![image](https://user-images.githubusercontent.com/63460537/187760124-22ec85d4-63bc-440b-9f67-0cebbdf119b1.png)

2022-08-31 18:56 UTC, dmncp commented
Ten sam error w zad bojowym :(

2022-08-31 18:57 UTC, dmncp requested changes
jw

2022-08-31 18:57 UTC, dmncp commented
Czy to może być wina wersji node'a? Daj mi znać na priv ;)

2022-08-31 19:41 UTC, kwdrt commented
Okazuje się że to nie node (a przynajmniej nie wydaje mi się), ale chyba ogarnąłem

Okazuje się że przy pierwszym (...i tylko pierwszym) emotion na `11.0.0` ma jakieś problemy, czyli dowolny ekran z animacjami wywali ten warn, ale tylko pierwszy. dlatego nie widziałem tego u siebie, bo już był pierwszy raz odpalony podczas testów, a to wywalało po wylogowaniu i dopiero zalogowaniu po raz kolejny, przynajmniej u mnie.

Teraz jest hardcoded najnowsza wersja `emotion` i nie ma problemów, przynajmniej nie znalazłem

2022-08-31 20:28 UTC, dmncp approved these changes
teraz wszystko super :)

2022-08-31 20:28 UTC, merged