[Sc-160] Endpointy do dodania nowej aktywności
ajablonsk1/systematic-chaos pull request #147
Opened 2022-08-29 16:56 UTC by ajablonsk1

Dobra trochę się napociłem przy tym tasku więc się rozpiszę, żebyście nie musieli czytać kodu, bo jest go bardzo dużo.

(Do Bartka bardziej) Z małych zmian to nie wiem czemu w GraphTask był maxPoints100. maxPoints100 to jest maksymalna ilość punktów jaką mógł zdobyć student idąc swoją trasą. GraphTask to tylko definicja jak wygląda ekspedycja, za to GraphTaskResult to rezultat dla danego studenta i on wie jaką trasą szedł student i tam powinnon być maxPoints100. Zmieniłem więc maxPoints100, żeby był w GraphTaskResult i naprawiłem statystyki. Sprawdź proszę, czy czegoś innego to nie rozwali, ale wydaje mi się, że już git działa wszystko z tą zmianą.

Z wiekszych zmian to:
1. Dodałem 8 endpointów (4 GET do zaciągania przykładowego jsona, 4 POST do tworzenia aktywności):
    - GET api/task/file/create
    - POST api/task/file/create
    - GET api/task/graph/create
    - POST api/task/graph/create
    - GET api/info/create
    - POST api/info/create
    - GET api/survey/create
    - POST api/survey/create
 
Jak dokładnie działają i co przyjmują to możecie na swaggerze zobaczyć, bo jakbym miał sie tu rozpisać to XD. 

Ważne jest to, że jako ten json jest modyfikowalny przez profesora to może sobie w teorii tam wpisać co chce i może coś się wywalić dlatego zrobiłem walidatory do przyjmowanych jsonów. Jeżeli prowadzący czegoś zapomni (lub np. da tylko jedno pytanie w całej ekspedycji) to zwracany jest obiekt Error, który wygląda tak (to już wczeniej było, ale przypominam):
<img width="495" alt="image" src="https://user-images.githubusercontent.com/73038429/187252499-782539b1-2bea-4e88-b423-6ff800de96bb.png">
Taskże z response errora z pola message możecie sobie wziąć te opisy do wyświetlania wiadomości dla użytkownika (kiedyś Damian coś takiego robił, dlateo pomyślałem, że tu tez się może przydać).

Jedyne co mogę wspomieć o tym jsonie co robi prowadzący, to że przy GraphTasku jest przy pytaniach jest pole questionNum. Zrobiłem to tak, że pierwsze pytanie musi mieć questionNum: 0 (jak nie ma to jest zwracana ładnie informacja) i to pierwsze pytanie to jest to startowe, które wsm nie jest pytaniem, ale jest użyteczne do wskazania jakie inne pytania są na poczatku do wyboru (pole nextQuestions). I tak zrobiłem to tak, że prowadzący sam sobie ustawia ten questionNum i potem na podstawie tych question num w innych pytaniach w polu nextQuestions wpisuje numery pytań, które będą do wyboru po tym aktualnym pytaniu (chyba się zamotałem XD). 

Dobra już nie przedłużam, jak cos to w tych getach sobie sprawdźcie przykładowe obiekty i jak jakieś pytania i uwagi to walcie bo to wsm ważny task.

2022-08-29 18:56 UTC, barto14753 commented
Po stronie frontu przy pytaniach zamkniętych coś się sypie (chyba, że nie jest to jeszcze zintegrowane), pytania otwarta działają.
<img width="1440" alt="Zrzut ekranu 2022-08-29 o 20 11 26" src="https://user-images.githubusercontent.com/56938330/187269608-78391d0f-70bd-4d6c-9b7a-e81d9f268da2.png">

Wrzuciłem drobny fix po tych zmianach z maxPointsami dla graphTaska. Potestowałem endpointy i poza tym problemem z zamkniętym pytaniem na froncie wszystko wydaje się być git

2022-08-29 18:58 UTC, barto14753 approved these changes
LGTM

2022-08-30 15:22 UTC, kwdrt commented
Sprawdziłem wszystkie rodzaje aktywności - ankiety, fileTaski i info działają, ale jest problem z ekspedycjami jak zauważył Bartek - wygląda jakby nie pobierało prawidłowo odpowiedzi na pytania, np. tutaj z przykładami w ekspedycji z przykładowej podanej na endpoincie. Dane zbierane z /question po id pytania.

![firefox_q7fE3jUjRX](https://user-images.githubusercontent.com/56168780/187476312-724a90d1-189f-4b79-ab97-1299c14ab9cb.png)

![obraz](https://user-images.githubusercontent.com/56168780/187476397-d6b0c6cf-eab8-4fa8-b93e-7b27d57a0389.png)

2022-08-30 15:24 UTC, kwdrt requested changes
@up

2022-08-30 16:56 UTC, ajablonsk1 commented
Powinno śmigać, zapomniałem w jednym miejscu ustawić pytania dla odpowiedzi.

2022-08-30 17:09 UTC, kwdrt approved these changes
Sprawdziłem i wydaje się że wszystko teraz działa tak jak powinno, dobra robota 👍

2022-08-30 17:40 UTC, merged