[SC-164] Widok do dodania nowego rozdzialu
ajablonsk1/systematic-chaos pull request #149
Opened 2022-08-30 16:06 UTC by kwdrt

Jak w tytule - na razie prosty modal zgodny z endpointem.

Do testów - mamy pusty plik o id: 1

Przy okazji wydzieliłem SuccessModal do oddzielnego komponentu, bo w sumie czemu nie jeśli jest używany w paru miejscach prawie bez zmian - zostawiłem na razie tylko ten w JSONEditorze, bo miał parę zmian względem reszty, ale jego też mogę zwinąć do tego jeśli to dobry pomysł.

![firefox_MyGtCN4YaY](https://user-images.githubusercontent.com/56168780/187486078-6edfef43-be1c-4554-ab51-b23d47d26c92.png)

![firefox_8xDBIHKMwQ](https://user-images.githubusercontent.com/56168780/187486103-09e6cd0d-9bb5-4540-a829-5e52affc2c37.png)

2022-08-30 16:55 UTC, dmncp requested changes

2022-08-30 16:55 UTC, dmncp commented on frontend/src/components/professor/GameManagement/AddChapterModal/AddChapterModal.js
> +                .catch(() => {})
ja bym chyba wyświetlał error message który przychodzi z backendu (pod formularzem)

2022-08-30 16:55 UTC, dmncp commented on frontend/src/components/professor/GameManagement/AddChapterModal/AddChapterModal.js
> +                        )}
Jak wyrzuci błąd z backendu to spinner już zostanie. Trzeba zmienić isSubmitting w catchu wyżej

2022-08-30 16:55 UTC, dmncp commented on frontend/src/components/professor/GameManagement/AddChapterModal/AddChapterModal.js
> +            }}
Narzuć takie nasze wewnętrzne umowne górne ograniczenie na sizeX i sizeY na np 10. Bo wyobraź sobie że ktoś poda wymiar 100x100. Wtedy mamy taką mapę aktywności:
![image](https://user-images.githubusercontent.com/63460537/187495002-dc563eaa-1722-4d35-a91c-86feb80d9d47.png)

2022-08-30 16:55 UTC, dmncp commented on frontend/src/components/professor/GameManagement/AddChapterModal/AddChapterModal.js
> +                })
Brakuje mi odświeżania widoku po zamknięciu success modala (pobranie ponownie zawartości niestety)

2022-08-30 16:56 UTC, dmncp commented
Dodatkowo zmień już w pliku ChapterDetails w linii 54 z 1 na chapterId, teraz jest już to możliwe

2022-08-30 17:19 UTC, kwdrt commented on frontend/src/components/professor/GameManagement/AddChapterModal/AddChapterModal.js
> +            }}
test na wzrok, fajny

2022-08-31 19:06 UTC, dmncp requested changes
Jakbym miał patrzeć na kod to by było spoko, ale mam dwie uwagi. Jedna bardzo drobna, a druga baardzo poważna.
1. Nie wiem czy nie zmniejszyć tego limitu na x, y do 10 bo już w chapterDetails ta mapa wygląda trochę słabo dla mnie. Subiektywna opinia więc potestuj i zobacz jak będzie jeszcze dobrze wyglądała
2. Jest mega poważna luka, w widoku zarządzania grą lecą zapytania do api w nieskończoność o listę chapterów (masz szczęście że mi komputer nie wybuchł xD):
![image](https://user-images.githubusercontent.com/63460537/187761964-36aeb598-0616-4060-bac0-3a86f9766828.png)

2022-09-01 16:20 UTC, dmncp approved these changes

2022-09-01 16:20 UTC, merged