[SC-221] Endpoint na listę możliwych zdjęć dla rozdziału
ajablonsk1/systematic-chaos pull request #150
Opened 2022-08-31 15:09 UTC by ajablonsk1

Dodałem endpointa do zdjęć dla rozdziału. Zdjęcia są przechowywane w nowej tabeli, zdjęcia dla rozdziału maja ImageType.CHAPTER (może potem jakieś inne typy będą).

GET api/file/chapter/images

[
    {
        "id": 2,
        "name": "Chapter image 1",
        "file": <bardz długi ciąg znaków>
        "type": "CHAPTER"
    }
]

2022-09-01 16:23 UTC, kwdrt commented
Nie jestem do końca pewien czy problem jest po mojej stronie, chociaż raczej nie powinien jeśli to docker - nie chce się zbudować:

![obraz](https://user-images.githubusercontent.com/56168780/187964460-3653ae14-9878-45ff-9518-9d437ba351c9.png)

2022-09-01 16:26 UTC, kwdrt requested changes
jw

2022-09-02 12:22 UTC, ajablonsk1 commented
Dobra, wiem czemu. Problem leży w tym, że aktualnie baza nam się buduje wraz ze startem aplikacji i przez to umieściłem plik ze zdjęciem w resources i przy budowaniu backendu przez Dockera to sie pluje, że tego pliku nie ma, zaraz dodam.

2022-09-03 09:45 UTC, kwdrt commented
Jeszcze myślę że nie ma sensu dawać listy plików i plików w tym samym - wtedy każdy request na tą listę będzie mieć np. 5MB i zajedziemy transfer kompletnie, lepiej dać listę samnych id z nazwą i łapać potem konkretne id wartości

2022-09-04 16:58 UTC, kwdrt approved these changes
Wygląda dobrze 👍 

Sprawdziłem jak działa łapanie tego na endpointach i powinno być ok

2022-09-04 17:30 UTC, merged