[SC-212] Endpoint na podsumowanie gry
ajablonsk1/systematic-chaos pull request #155
Opened 2022-08-31 20:45 UTC by barto14753

Endpoint /summary - pełny opis: https://systematic-chaos.atlassian.net/jira/software/projects/SC/boards/1?selectedIssue=SC-212 . Jak coś to brane pod uwagę są aktywności, których ownerem jest requestujący professor

2022-09-01 08:40 UTC, dmncp commented
Mam wątpliwość co do działania tego endpointa. To nie uwaga ale pytanie do @barto14753 oraz @ajablonsk1.
Teraz ten endpoint działa tak, że jak student zrobi jakąś aktywność typu zadanie bojowe, którą prowadzący musi sprawdzić, to jeden prowadzący ma np 2 aktywności do sprawdzenia, a drugi ma 0. Od czego zależy, że ta konkretna aktywność trafi do tego konkretnego prowadzącego, a do innego nie ?

2022-09-01 08:43 UTC, dmncp approved these changes
Poza tym jednym pytaniem, które zadałem wyżej - nie mam uwag, działa superowo i tak jak chciałem. Naprawdę dobra robota 🥳❤️.
UWAGA: zrobiłem review tylko samego działania, a nie kodu. Poczekaj na review Adiego, żeby zrobić merge.

2022-09-01 09:14 UTC, ajablonsk1 requested changes
Działanie git, ale te odwołania do klas i instanceof to bad habity, wiec postaraj się zrefactorować, aby tego nie używać. (możesz przy okazji też to co kiedyś używałeś instanceof poprawić)

2022-09-01 09:14 UTC, ajablonsk1 commented on api/src/main/java/com/example/api/dto/response/map/task/ActivityType.java
> +    public static ActivityType getActivityType(Activity activity) {
Chyba ładniej takie coś zrobić w samych aktywnościach, typu zrobic w GraphTask, FileTasku itd getActivityType i on by zwracał odpowiedni enum, bo te odwołania do klas mi smierdzą trochę.

2022-09-01 09:14 UTC, ajablonsk1 commented on api/src/main/java/com/example/api/util/csv/PointsToGradeMapper.java
> +    public Double getMaxPoints(TaskResult taskResult) {
KIedyś używałeś instanceof i stwierdziłem, że git, ale jak już drugi raz to imo za dużo. Na szybko wygooglowałem to co myśle, że to bad habit jest no i stackoverflow potwierdziło. 

https://stackoverflow.com/questions/3776862/when-should-and-shouldnt-instanceof-be-used

Spróbuj to zrefactorować, żeby tego nie było.

2022-09-01 09:16 UTC, ajablonsk1 commented
> Mam wątpliwość co do działania tego endpointa. To nie uwaga ale pytanie do @barto14753 oraz @ajablonsk1. Teraz ten endpoint działa tak, że jak student zrobi jakąś aktywność typu zadanie bojowe, którą prowadzący musi sprawdzić, to jeden prowadzący ma np 2 aktywności do sprawdzenia, a drugi ma 0. Od czego zależy, że ta konkretna aktywność trafi do tego konkretnego prowadzącego, a do innego nie ?

Aktualnie aktywność jest przypisana do prowadzącego, który ją stworzył. Pewnie te resulty, które dotyczą jego aktywności idą do niego po prostu na sprawdzenie. Można to zmienić lub zrobić jakiś dod feature, żeby mogł przepisywać niektóre do sprawdzenia dla innego prowadzącego.

2022-09-01 09:21 UTC, dmncp commented
> Aktualnie aktywność jest przypisana do prowadzącego, który ją stworzył. Pewnie te resulty, które dotyczą jego aktywności idą do niego po prostu na sprawdzenie. Można to zmienić lub zrobić jakiś dod feature, żeby mogł przepisywać niektóre do sprawdzenia dla innego prowadzącego.

Myślę że na razie jest git. W sumie logiczne, że tak to działa :)

2022-09-01 15:11 UTC, dmncp requested changes
Jednak trzeba dodać jeszcze mediany, w jirze naniosłem zmiany

2022-09-03 18:57 UTC, barto14753 commented
Dodałem mediany i wywaliłem instanceofy. Część instanceof'ów zastąpiłem sprawdzaniem activityType (czyli właściwie wychodzi na to samo) bo nie mogłem nic innego wymyślić. Poprzenosiłem też niektóre funkcje z serwisu (np. to liczenie średniej, mediany), wywaliłem niewykorzystywane rzeczy i naprawiłem to wywoływanie dwóch tych samych filtrów zamiast dwóch róznych w getAlllProfessorChapterActivities

2022-09-04 11:50 UTC, dmncp approved these changes
Co do działania - jest git. Co do kodu - poczekaj na review.

2022-09-04 16:01 UTC, ajablonsk1 approved these changes
Mimo wszystko te ActivityType wyglądają lepiej niż instanceof, więc najs. LGMT

2022-09-04 16:35 UTC, merged