[SC-239] Dodanie pola completed dla responsu /map
ajablonsk1/systematic-chaos pull request #163
Opened 2022-09-04 12:59 UTC by barto14753

Dodałem pole isCompleted dla responsu /map. Z tego endpointa korzystają zarówno studenci jak i prowadzący. Dla studentów isCompleted ustawiany jest na podstawie odpowiednich resultów a dla. profesorów to pole będzie false. Info dla studentów zawsze jest isCompleted=true.

2022-09-04 16:17 UTC, ajablonsk1 approved these changes
Wywal nieużywany argument i reszta git chyba

2022-09-04 16:17 UTC, ajablonsk1 commented on api/src/main/java/com/example/api/service/map/ActivityMapService.java
> +    private boolean isInfoCompleted(Info info, User student) {
argument info jest nieużywany

2022-09-04 16:46 UTC, dmncp requested changes
Jest jeden błąd. Info task owszem ma zawsze zwracać true, ale dla studenta. Dla prowadzącego ma zwracać false jak wszystkie pozostałe aktywności (obecnie jest true).

2022-09-04 22:00 UTC, barto14753 commented on api/src/main/java/com/example/api/service/map/ActivityMapService.java
> +    private boolean isInfoCompleted(Info info, User student) {
wywaliłem go

2022-09-04 22:03 UTC, barto14753 commented
Teraz isCompleted info dla prowadzącego też jest false, wywaliłem nieużywany argument i zrobiłem drobny refactor funkcji od isCompleted

2022-09-05 15:09 UTC, dmncp approved these changes

2022-09-05 15:09 UTC, merged