[SC-54] Added database schema (almost everything - for now it will be ok)
ajablonsk1/systematic-chaos pull request #17
Opened 2022-05-25 22:01 UTC by ajablonsk1

Zrobiłem schemat bazy. Wzorowałem sie na tym co było zmockowane na froncie, ale też troche pozmieniałem. Jak komuś się chce to zapraszam do ogarnięcia i napisania czy czegoś nie pominąłem. Napewno nie dodałem jeszcze tabel do odznak - na razie nie jest to potrzebne.

2022-05-28 11:19 UTC, kwdrt commented
Good job! Gave the DB a look, and it looks good, the only thing I've noticed missing are access codes for groups, couldn't find those anywhere.

Posting a DataGrip DB export here to make it easier to see
![access_date](https://user-images.githubusercontent.com/56168780/170823235-d65cace9-8053-4f8f-9014-b949cd144ab6.png)

2022-05-28 11:20 UTC, kwdrt commented
Also I don't see chapters anywhere here for now, not sure if we're adding them now or later?

2022-05-28 11:24 UTC, kwdrt requested changes
Nie ma też tutaj uwzględnionych rozdziałów, ale nwm czy to w ogóle w scope tego co robimy teraz? Myślę że na razie można mergować, najwyżej dodamy/zmienimy coś potem, na razie nie widzę co (oprócz tych kodów).

Daj znać jak to widzisz i będzie można zrobić merge jak to ogarniemy.

2022-05-28 17:59 UTC, ajablonsk1 commented
Tak, masz racje zapomniałem i o kodach do grup i rozdziałach. Zaraz to poprawię.

2022-05-29 09:47 UTC, kwdrt commented
Wygląda ok, podrzucam obecny diagram:
![datagrip64_7JRg9biOpV](https://user-images.githubusercontent.com/56168780/170862017-dcc94bb9-f55b-43a9-a3da-8d61a6325107.png)

2022-05-29 09:47 UTC, kwdrt approved these changes

2022-05-29 21:18 UTC, merged