[SC-257] Dodanie pozycji rozdziału na mapie
ajablonsk1/systematic-chaos pull request #178
Opened 2022-09-14 20:44 UTC by barto14753

Teraz rozdział posiada posX i posY. Przy tworzeniu rozdziału sprawdzana jest unikalność. Dla obu getów chapterów zwracane jest w responsie pozycja.

2022-09-15 16:28 UTC, dmncp approved these changes

2022-09-15 16:28 UTC, dmncp approved these changes

2022-09-16 08:21 UTC, ajablonsk1 requested changes

2022-09-16 08:21 UTC, ajablonsk1 commented on api/src/main/java/com/example/api/service/validator/ChapterValidator.java
> +public class ChapterValidator {
W MapValidator dawalem metody do walidowania chaptera, wiec albo przenies je tu, albo to co jest tu tam.

2022-09-16 19:35 UTC, barto14753 commented
Przeniosłem jedną funkcję od walidacji chapter'a z MapValidator'a do ChapterValidator'a

2022-09-17 10:49 UTC, ajablonsk1 approved these changes

2022-09-17 11:05 UTC, merged