[SC-310] Bugi w summary endpoint
ajablonsk1/systematic-chaos pull request #234
Opened 2022-10-12 20:37 UTC by barto14753

Teraz /summary powinien zwracać prawidłową:
- listę aktywności do sprawdzenia(notAssessedActivitiesTable)
- liczbę nieocenionych aktywności (notAssessedActivityCounter) 
- liczbę ocenionych aktywności (assessedActivityCounter)
- liczbę odpowiedzi czekających do oceny (waitingAnswersNumber)

Jeśli zauważyliście jakieś inne bugi, których tu nie uwzględniłem to podrzućcie je

2022-10-12 21:03 UTC, dmncp requested changes
Coś jest jeszcze nie tak bo znalazłem buga.
Scenariusz odtworzenia:
1. Wchodzimy na maj i widzimy, że mamy 3 ocenione aktywności (btw nie jestem w stanie sprawdzić czy to poprawna wartość)
2. Sprawdzamy jedną aktywność którą mamy do sprawdzenia i licznik wskakuje na 4
3. Idziemy na kkruk i wykonujemy zadanie bojowe
4. Idziemy na murbanska i wykonujemy zadanie bojowe
5. wracamy na maj i widzimy że licznik ocenionych wrócił na 3
Nwm skąd ten błąd ale tak jest u mnie, daj znać czy jesteś w stanie powtórzyć to i czy też tak ci się dzieje

Jeżeli nie uda ci się powtórzyć tego buga i u ciebie będzie poprawnie to dam approve.

PS to może być dlatego że między punktem 2, a 3 zmieniłem wymagania dla zadania bojowego żeby było odblokowane dla studentów?

2022-10-12 22:50 UTC, barto14753 commented
> Coś jest jeszcze nie tak bo znalazłem buga. Scenariusz odtworzenia:
> 
> 1. Wchodzimy na maj i widzimy, że mamy 3 ocenione aktywności (btw nie jestem w stanie sprawdzić czy to poprawna wartość)
> 2. Sprawdzamy jedną aktywność którą mamy do sprawdzenia i licznik wskakuje na 4
> 3. Idziemy na kkruk i wykonujemy zadanie bojowe
> 4. Idziemy na murbanska i wykonujemy zadanie bojowe
> 5. wracamy na maj i widzimy że licznik ocenionych wrócił na 3
>    Nwm skąd ten błąd ale tak jest u mnie, daj znać czy jesteś w stanie powtórzyć to i czy też tak ci się dzieje
> 
> Jeżeli nie uda ci się powtórzyć tego buga i u ciebie będzie poprawnie to dam approve.
> 
> PS to może być dlatego że między punktem 2, a 3 zmieniłem wymagania dla zadania bojowego żeby było odblokowane dla studentów?

Licznik oceenionych (assessedActivityCounter) wskazuje obecnie ile jest aktywności, które mają wszystkie odpowiedzi ocenione (evaluated). Jeśli sprawdziłeś jedyną na ten moment odpowiedź w 2 punkcie, wtedy ta aktywność staje się assessed. Gdy w punkcie 3 i 4 wykonujesz aktywność i tworzysz odpowiedzi do sprawdzenia wtedy ta aktywność staje się notAsseessed i licznik sprawdzonych spada do 2 a niesprawdzonych do 4. Jak sprawdzisz wszystkie odpowiedzi dla tej jednej aktywność wtedy licznik sprawdzonych wzrośnie a spadnie nieocenionych. Przeszedłem flow tak jak to opisałeś i działa to tak jakbym przypuszczał, ale może te pola w responsie mają inne znaczenie niż mi się wydaje, więc możesz opisać jak ty to widzisz. Dla mnie wygląda to tak, że:
-  notAssessedActivityCounter -> liczba aktywności, które mają chociaż jedną nieocenioną odpowiedź
- assessedActivityCounter -> tak naprawdę to jest liczba wszystkich aktywności minus liczba ocenionych aktywności (więc jeśli aktywność ma wszystkie odpowiedzi ocenione lub nie otrzymała jeszcze żadnej to zalicza się do tej kategorii)
- waitingAnswersNumber -> liczba wszystkich nieocenionych odpowiedzi

2022-10-13 05:42 UTC, dmncp commented
Ok teraz rozumiem ;)

2022-10-13 05:42 UTC, dmncp approved these changes

2022-10-13 16:45 UTC, ajablonsk1 approved these changes
Git

2022-10-13 16:50 UTC, merged