[SC-335] HTTPS (self-signed cert dla obsługi szyfrowania requestów)
ajablonsk1/systematic-chaos pull request #258
Opened 2022-10-31 13:27 UTC by kwdrt

Obecnie wysyłamy requesty bez żadnego szyfrowania więc ktoś z np Wiresharkiem może je złapać po drodze w tej samej sieci (i ogólnie je podejrzeć “po drodze”) - przez dodanie self-signed certyfikatu na backendzie zapewnimy TLS.

Zmienione porty na których operuje backend (Spring Boot) z 8080 na 443 (domyślny HTTPS) w konfiguracji springa i Dockerfile/docker-compose które znalazłem w projekcie (8080:8080 -> 443:443)

Przykładowy request przed dodaniem SSL:
![firefox_zcInT6WlaG](https://user-images.githubusercontent.com/56168780/199018034-a261429a-e019-4466-92f0-b78ea4ee028a.png)

Przykładowy request po dodaniu SSL - pojawia się zakładka "Bezpieczeństwo":
![obraz](https://user-images.githubusercontent.com/56168780/199017758-714722f3-bc7b-4ec5-affd-710e9d3803b2.png)

Jeśli chodzi o front - obsługa certów tam powinna być zapewniona przez Vercel, więc nie powinno być z tym problemów.

Po odpaleniu Swaggera przeglądarka może krzyczeć o "SELFSIGNED_CERT" - nie jest to dla nas problem, mamy go tutaj po to żeby zapewnić szyfrowanie po drodze i to wystarcza - błąd z tego co widzę znika przy kolejnym odpaleniu.

2022-10-31 14:19 UTC, dmncp requested changes
Dla studenta w kakładce profil wywala errory u mnie:
![image](https://user-images.githubusercontent.com/63460537/199029364-9b72116e-bfd1-49c4-bfe1-0fee36ebcb96.png)
![image](https://user-images.githubusercontent.com/63460537/199029400-756abbfd-860d-4bb5-90e9-14798ebafbc2.png)

2022-10-31 14:25 UTC, kwdrt commented
> Dla studenta w zakładce profil wywala errory u mnie: ![image](https://user-images.githubusercontent.com/63460537/199029364-9b72116e-bfd1-49c4-bfe1-0fee36ebcb96.png) ![image](https://user-images.githubusercontent.com/63460537/199029400-756abbfd-860d-4bb5-90e9-14798ebafbc2.png)

na jakiej przeglądarce?

2022-10-31 14:34 UTC, kwdrt commented
Muszę zbadać sprawę z CA, wygląda na to że nie przejdzie bez tego bo przeglądarki blokują requesty na endpoint z self-signed certem

2022-10-31 14:37 UTC, dmncp commented
> na jakiej przeglądarce?

Chrome

2022-11-01 11:38 UTC, kwdrt commented
Zbadałem sprawę i... najprościej (pojęcie względne) było kupić domenę - więc teraz instancja zdeployowana jest pod adresem systematic-chaos-backend.xyz

Wada tego rozwiązania jest taka, że ciężko wrzucić te rzeczy bezpośrednio do repo, zaleta - teraz jak rozstawiłem rzeczy i wiem jak to się robi to powinno mi zajmować może 10 minut, a nie 8h jak już będziemy stawiać "ostateczną" wersję do testów.

Postaram się jeszcze spisać te rzeczy związane z procesem żeby zmniejszyć tzw. bus factor i ogarnąć jakiś password vault żeby każdy miał dostęp do naszej maszyny na Google Cloud w bezpieczny sposób, np. przez cert do SSH na naszą maszynę... albo może uda mi się dodać wszystkich jako collaboratorów do projektu na GC z odpowiednimi uprawnieniami.

2022-11-11 19:01 UTC, kwdrt commented
Zamykam PR, zmiany rozwiązujące problem rozwiązuję ręcznie na deployu - nie chcę wrzucać certów tu do repo

2022-11-11 19:01 UTC, closed without merging