[SC-336] Nie działa flaga forGroup
ajablonsk1/systematic-chaos pull request #261
Opened 2022-10-31 20:01 UTC by ajablonsk1

Flaga dziala jak powinna, ale moze to nie bylo zbyt klarowne jak to dziala.

forGroup jest tylko dla odznaki top_score bo dla kazdej innej nie ma sensu.

Dodalem tutaj mala zmiane aby w /all tylko dla top_score zwracalo pole forGroup i zeby nie bylo nulli

2022-10-31 20:26 UTC, dmncp approved these changes

2022-10-31 20:39 UTC, dmncp requested changes
jednak daję blocka na chwilę, muszę coś sprawdzić

2022-10-31 20:47 UTC, dmncp commented
Kilka uwag:
1. W `/add` pole dla `image` nie może być optional. Miało być optional tylko w endpointach `/update`
2. W '/add` pole `type` chyba powinno być required. Jeżeli nie to proszę o wyjaśnienie ;)
3. Jeżeli dodam odznakę typu `TOP_SCORE`, ale nie podam `forGroup` (bo jest optional) to chcę żeby to było traktowane jako false i żeby gety zwracały wtedy false, a nie null jak obecnie

2022-11-01 09:05 UTC, ajablonsk1 commented
> Kilka uwag:
> 
> 1. W `/add` pole dla `image` nie może być optional. Miało być optional tylko w endpointach `/update`
> 2. W '/add`pole`type` chyba powinno być required. Jeżeli nie to proszę o wyjaśnienie ;)
> 3. Jeżeli dodam odznakę typu `TOP_SCORE`, ale nie podam `forGroup` (bo jest optional) to chcę żeby to było traktowane jako false i żeby gety zwracały wtedy false, a nie null jak obecnie
> 4. Prośba przy okazji - czy dałbyś radę dodać sortowanie odznak w `/all` po id ? Bo po edycji odznaki przeskakuje ona na sam koniec listy w endpoincie i to słabo wygląda :/

1. @Schema(required=true/false) jest tylko dla czytelności nie zmienia nic w kodzie i nie wymusza zeby pola z true serio byly. Używam tego samego dto do /add i /update, wiec albo true albo false. Dalem na dalse bo do update nie musi byc, ale tak jak pisalem wczesniej to nic nie zmienia nawet jakbym dal true to i tak w teorii nie musisza wyslac i tak przejdzie.
2. Tutaj po prostu nie dopisalem tego @Schema a bazowo jest na false. Powinno byc na true.
3. Done
4. Done

2022-11-01 16:42 UTC, dmncp approved these changes

2022-11-01 17:00 UTC, merged