[SC-62] Komponent na wyświetlanie listy aktywności i liczby zdobytych w nich punktów
ajablonsk1/systematic-chaos pull request #38
Opened 2022-06-11 21:07 UTC by barto14753

Komponent zawiera :
- listę sprawdzonych aktywności, 
- listę wykonanych aktywności czekających na ocenę (oceny zgodnie ze skalą AGH-owską),
- kilka statystyk

Dodałem też do sidebaru link do niego (w wersji mobilnej zrobiło się trochę ciasno, najwyżej w przyszłości połączy się go z komponentem punktów)

2022-06-12 11:21 UTC, dmncp requested changes
Jest kilka większych uwag do poprawienia i kilka propozycji zmian.

2022-06-12 11:21 UTC, dmncp commented on frontend/src/components/Grades/GradesTable.js
> +                    <th>Typ aktywności</th>
Ja bym to zrobił nieco inaczej:
```js
const headers = ['Nr', 'Aktywność', 'Ocena', 'Punkty', 'Data', 'Typ aktywności']
```
i potem w tagu `<tr>`:
```jsx
<tr>
    {headers.map(header => (
        <th>header</th> // nie zapomnij o key
    ));}
<tr>
```
Chodzi o ideę, jak się machnąłem w kodzie to odpowiednio dopasuj

2022-06-12 11:21 UTC, dmncp commented on frontend/src/components/Grades/UnmarkedActivitiesTable.js
> +                </tr>
Analogicznie jak wyżej można wykorzystać listę `header` (tylko wrzuć ją w constatns.js)

2022-06-12 11:21 UTC, dmncp commented on frontend/src/components/Grades/GradesTable.js
> +                        <td>{getActivityTypeName(row.activityType)}</td>
To też bym wyciągnął jak wyżej. Dodatkowo bardzo podobnie wygląda to w `UnmarkedActivitiesTable.js`. Jedyny pomysł jaki mam w tej chwili jak to zrobić jest następujący:
```js
const TableType = {
    GRADES_TABLE: 0,
    UNMARKED_ACTIVITIES_TABLE: 1
};

const TableContent = (tableType, row, idx) => {
    id: idx + 1,
    name: row.activityName,
    points: tableType === TableType.GRADES_TABLE 
        ? percentagesToGrade(row.points / row.maxPoints) 
        : row.maxPoints,
    date: row.date,
    activityType: getActivityTypeName(row.activityType)
}
```
No i wtedy można analogicznie rozpisać mapper na `<tr>`. To taki pomysł na szybko, w dodatku nietestowany. Jeżeli ktoś wymyśli coś lepszego to zapraszam do dyskusji 😉

2022-06-12 11:21 UTC, dmncp commented on frontend/src/components/Grades/UnmarkedActivitiesTable.js
> +                    </tr>
Można wykorzystać zmienną `TableContent` (przy okazji sprawdź czy jakiś komponent / element nie ma już takiej nazwy 😅). Dodatkowo mając już takie mappery te dwa komponenty (`UnmarkedActivitiesTable` oraz `GradesTable`) wyglądają bardzo podobnie o ile nie tak samo, więc proponuję wyciągnąć jak najwięcej powtarzającego się kodu do nowego komponentu i z niego korzystać w tych komponentach

2022-06-12 11:21 UTC, dmncp commented on frontend/src/storage/gradesTable.js
> +        date: '10.04.2022',
Co do dat to zapytał bym Adriana jak wygląda format dat na backendzie i w bazie. Może np być coś w stylu '2022-04-10'. Jeżeli inny format zapisu daty nie zmieni Twojej koncepcji to okej, ale jak zmieni to dogadajcie się jak ma to wyglądać, żeby później bezboleśnie przechodzić z mocków na endpointy

2022-06-12 11:21 UTC, dmncp commented on frontend/src/components/Grades/GradesTable.js
> +                        <td>{getActivityTypeName(row.activityType)}</td>
W sumie możesz też wykorzystać moment.js do wyświetlania dat. Gdy zamiast `row.date` napiszesz `moment(row.date).calendar()` to data, która zawiera godzinę może się wyświetlać np tak: "Dziś o 17:40", albo "Wczoraj o 13:25" itp. I prawdopodobnie jakby nie było godzin to takie daty bliskie "dzisiejszej" wyświetlały by się w stylu: "Dzisiaj", "Wczoraj". 
Tutaj dodatkowa uwaga: domyślnie wyświetla się data po angielsku. Żeby mieć polski wystarczy zapisać: 
 ```js
import moment from "moment";  // żeby po prostu skorzystać z moment.js
import 'moment/locale/pl';  // żeby zmienić na j.polski
 ```
 Jest to oczywiście tylko bajer/wodotrysk. Możesz to pominąć lub dodać według uznania 😉

2022-06-12 11:21 UTC, dmncp commented on frontend/src/storage/gradesTable.js
> +    return avgGrade.toFixed(1);
Wow, nie znałem tego, fajny bajer :D

2022-06-12 11:21 UTC, dmncp commented on frontend/src/utils/constants.js
> +        return 3.0 + Math.floor((percentages - 0.5) / 0.1) * 0.5;
Wyciągnij te cyfry do zmiennych, które opisują znaczenie tych cyfr. Łatwiej będzie sie taki kod czytało. Takie zapisanie jak zrobiłeś nazywa się chyba 'magic numbers' 😉 
(https://jeffreyeverhart.com/2020/09/28/javascript-tips-using-named-constants-for-magic-numbers/)

2022-06-13 21:02 UTC, barto14753 commented
Zmieniłem sposób generowania tych dwóch tabel, usunąłem 'magic numbers' z funkcji liczącej oceny oraz dodałem moment.js do wyświetlania dat w tabelach.

2022-06-14 10:44 UTC, dmncp requested changes

2022-06-14 10:44 UTC, dmncp commented on frontend/src/components/Grades/GradesTables.js
> +    ];
Zauważ, że ta zmienna `headers` zawiera praktycznie to samo co `headers` w GradesTable. Jedyna różnica to "Punkty" vs "Punkty do zdobycia" i w GradesTable ma jeszcze "Oceny". Ja bym zrobił jedną zmienną headers, która nie zawiera "Oceny" i tylko dopisywać w GradesTable. Bo po co tak powtarzać 😅

2022-06-14 10:44 UTC, dmncp commented on frontend/src/components/Grades/GradesTables.js
> +};
Takie rzeczy i inne, które się pojawiły powinny znaleźć się w `constants.js`

2022-06-14 12:20 UTC, barto14753 commented
Przeniosłem GradesTableType do constants.js i zrefacktorowałem sposób przekazywania nagłówków i contentu do tabel.

2022-06-14 14:31 UTC, dmncp requested changes

2022-06-14 14:31 UTC, dmncp commented on frontend/src/components/Grades/GradesTables.js
> +            : []),
A tutaj jak masz w linijce 39 pustą listę to nie możesz tam wrzucić "Punkty do zdobycia" i wyrzucić linijki 40-42 ?

2022-06-14 17:00 UTC, dmncp approved these changes
Okej, teraz wygląda super :D 
Tylko rozwiąż sobie konflikty w niektórych plikach

2022-06-14 17:06 UTC, merged