frontend refactor
ajablonsk1/systematic-chaos pull request #48
Opened 2022-07-02 16:22 UTC by dmncp

Zrobiłem mały refactor na froncie. Pewnie da się poprawić jeszcze więcej rzeczy, więc zapraszam do komentowania ;)

2022-07-03 13:02 UTC, kwdrt commented
Struktura bardzo mi się podoba, grupowanie po stronach to coś czego rzecywiście brakowało - split serwisów i podział na professor/student też dobry, dużo łatwiej będzie szukać rzeczy (i już w sumie jest przy tym jak przeglądałem projekt na tym branchu). Widzę też sporo usunięć "martwego" kodu, fajnie że wyleci sporo rzeczy które niepotrzebnie wiszą dalej w projekcie. Wygląda też że projekt dalej cały działa, więc chyba nic się nie popsuło.

TL;DR - Wygląda dobrze, dla mnie gotowe na merge

2022-07-03 13:02 UTC, kwdrt approved these changes

2022-07-03 14:33 UTC, barto14753 commented
<img width="1440" alt="Zrzut ekranu 2022-07-3 o 16 28 23" src="https://user-images.githubusercontent.com/56938330/177044242-842e9d1f-edc3-45e4-8f9a-1ddcf77d4d4c.png">
W widoku Oceny nie wyświetla się u mnie nazwa aktywności. Wydaje mi się, że w pliku gradesTable.js trzeba pozmieniać w zamockowanych danych activityType na Activity.EXPEDITION, Activity.TASK itd.

2022-07-03 14:34 UTC, barto14753 requested changes
<img width="1440" alt="Zrzut ekranu 2022-07-3 o 16 34 23" src="https://user-images.githubusercontent.com/56938330/177044514-29349649-fcea-4147-998f-25ab7358715f.png">
W widoku Oceny nie wyświetla się u mnie nazwa aktywności. Wydaje mi się, że w pliku gradesTable.js trzeba pozmieniać w zamockowanych danych activityType na Activity.EXPEDITION, Activity.TASK itd.

2022-07-04 08:35 UTC, dmncp commented
> <img alt="Zrzut ekranu 2022-07-3 o 16 34 23" width="1440" src="https://user-images.githubusercontent.com/56938330/177044514-29349649-fcea-4147-998f-25ab7358715f.png">
> 
> W widoku Oceny nie wyświetla się u mnie nazwa aktywności. Wydaje mi się, że w pliku gradesTable.js trzeba pozmieniać w zamockowanych danych activityType na Activity.EXPEDITION, Activity.TASK itd.

Było dokładnie tak jak opisałeś, już to naprawiłem

2022-07-04 16:40 UTC, barto14753 approved these changes
Bardzo fajna struktura katalogów (podział na studenta i prowadzącego) oraz rozbicie serwisów do osobnych plików znacznie poprawiło czytelność projektu.

2022-07-04 16:55 UTC, merged