[SC-98] Added group users endpoint
ajablonsk1/systematic-chaos pull request #59
Opened 2022-07-16 21:13 UTC by barto14753

Endpoint po podaniu ID zwraca liste userów danej grupy (tylko id, firstName i lastName). Dla wartości ujemnych endpoint zwraca wszystkich userów (tak jak to było w wymaganiach). Nie wiem tylko czy powininem dodać info o grupie danego usera, gdy zwracana jest lista wszystkich userów (teraz tego nie ma)

2022-07-17 18:27 UTC, ajablonsk1 requested changes
Trochę się rozpisałem w komentarzach, ale radzę przeczytać. Daje request changes, bo nie jestem pewien czy masz dobrze te funkcje w serwisie co ją skomentowałem. Jeżeli chodzi o testy to na razie nie musisz ich poprawiać (napewno zrobimy to później) - chyba, że chcesz.

2022-07-17 18:27 UTC, ajablonsk1 commented on api/src/main/java/com/example/api/service/group/GroupService.java
> +            return groupRepo.findAll()
Zwrócisz tutaj WSZYSTKICH userów, nie wiem czy Damianowi nie chodziło w tamtym opisie o wszystkich userów, ale dla danego prowadzącego.

2022-07-17 18:27 UTC, ajablonsk1 commented on api/src/main/java/com/example/api/service/group/GroupService.java
> +            return groupRepo.findAll()
@dmncp

2022-07-17 18:27 UTC, ajablonsk1 commented on api/src/main/java/com/example/api/service/group/GroupService.java
> +        Optional<Group> groupOptional = groupRepo.findById(id);
Własnie ostatnio rozważałem, czy nie zrobić refacotru i nie zamienić wszyskiego na optionale (w sensie ze tych findów), chociaż za bardzo ich nie lubię, ale do rozważenia.

2022-07-17 18:27 UTC, ajablonsk1 commented on api/src/test/java/com/example/api/service/group/GroupServiceTests.java
> +        when(groupRepo.findById(group1.getId())).thenReturn(Optional.ofNullable(group1));
No tak jak pisałem Ci na dc dzisiaj wydaje mi się, że te testy do serwisu są błędne, ponieważ nie sprawdzasz tu co sie dzieje w serwisach, tylko to co tak naprawdę robią repozytoria (a do nich bedą osobne testy).

Tutaj:
1. Podajesz, że gdy wykonasz `groupRepo.findById(group1.getId())` to ma Ci zwrócić group1.
2. (Niżej) Wykonujesz `groupService.getGroupUserList(group1.getId())`
i sprawdzasz czy return zgadza się z tym co oczekujesz.
3. To działa tak, że ustawiasz co ma Ci zwrócić, a potem sprawdzasz czy serio Ci to zwraca (chociaż sam to ustawiłeś). Znaczny no tu jest troche inaczej bo jeszcze na tym group1 robisz jakieś operacje, ale sam zamysł pozostaje ten sam.

Wrzuciłem tego mojego PR'a testy, których ja sie uczyłem. Uczyłem się tego jakoś daaawno temu między innymi z tego filmiku: https://www.youtube.com/watch?v=Geq60OVyBPg&t=4091s, ale to bardzo w podobny sposób testujemy w pracy.

Głównie chodzi o to, aby to co nam zwracają repozytoria w serwisie sobie ustawiać właśnie przez when().thenReturn, albo jak ja robilem given().willReturn. Następnie za pomocą ArgumentCaptora łapiemy sobie te argumenty, które były wykorzystane w tej funkcji i sprawdzamy czy się zgadzaja z tymi co ześmy dali jako prawdziwe argumenty. 

Jeżeli chodzi o to co zwraca serwis to, jeżeli jest to np. repo.save(entity). To wtedy nas nie interesuje za bardzo to, ponieważ zwraca coś z repa i to przy testach repo będziemy sprawdzać czy rzeczywiscie epo.save(entity) zwraca to dobre entity. A w testach serwisu sprawdzamy, czy rzeczywiscie te obiekty i argumenty, które tam złapiemy to rzeczywiście są te, które tam daliśmy lub stworzyliśmy.

Oczywiście to nie jest zawsze i w zależnosci od serwisu się powinno robić testy, bo niektóre zwracają co innego i wtedy trzeba posprwadzać odpowiednio wszystko (dopóki wciąż należy to dp zakresu zadań danego serwisu)

Troche się rozpisałem, ale może to rozwieje wątpliwości - jak masz uwagi, bo gadam głupoty, albo chcesz żebym Ci wytlumaczył to hit me up!

2022-07-17 18:38 UTC, dmncp commented on api/src/main/java/com/example/api/service/group/GroupService.java
> +            return groupRepo.findAll()
Mamy dwa rodzaje tabel na froncie: tabela studentów z danej grupy zajęciowej i tabela z wszystkimi studentami w systemie.  Chcemy mieć więc dwa endpointy: pierwszy zwraca wsystkich studentów z podanej grupy zajęciowej (podamy wam nazwę grupy bo musi być unikalna i oczekujemy imienia, nazwiska i id studenta - id żeby wam podać w wypadku gdy prowadzący zechce zmienić mu grupę zajęciową na inną) i drugi zwracający wszystkich userów w systemie (tutaj potrzebujemy oprócz imienia, nazwiska i id również nazwę grupy do której jest przypisany aktualnie)

2022-07-17 18:48 UTC, ajablonsk1 commented on api/src/main/java/com/example/api/service/group/GroupService.java
> +            return groupRepo.findAll()
Okej, dogadałem jeszcze z Damianem na priv. Mają być dwa endpointy, jeden na studentów należących do danej grupy zajęciowej, a drugi do WSZYSTKICH studentów po prostu. Teraz wgl jak to przemyślałem, to oba chyba powinny być w serwisie UserService (napewno ten z samymi studentami, po po prostu wyciągamy wszystkich userów, którzy mają AccountType == AccountType.STUDENT).

2022-07-18 17:33 UTC, barto14753 commented
Przeniosłem zwracanie listy wszystkich studentów z ich grupami do nowego endpoint'a (/students-with-group/all) w user controllerze

2022-07-18 20:59 UTC, ajablonsk1 approved these changes
LGTM. Jak sprawdziłeś czy wszystko działa to można mergować.

2022-07-18 21:45 UTC, merged