[SC-126] Widok główny rozdziału u prowadzącego
ajablonsk1/systematic-chaos pull request #74
Opened 2022-07-23 14:14 UTC by dmncp

W tym tasku zrobiłem widok zarządzania rozdziałem dostępny z panelu zarządzania grą po kliknięciu w wybrany wiersz tabeli rozdziałów.
Umieściłem w nim też podgląd mapy wybranego rozdziału. Zrodziło to wiele problemów, dlatego że musiałem zmodyfikować komponent odpowiedzialny za wyświetlanie mapy w taki sposób, żeby mapa dopasowywała się do rozmiaru rodzica, a nie do rozmiaru całego okna przeglądarki. Żeby to było możliwe przeniosłem kod generujący wymiary kafelka z komponentu kafelka do komponentu mapy i napisałem od zera generator wymiaru kafelka. Dodałem też możliwość wyłączenia klikalności kafelków na mapie. Przy okazji znalazłem buga powodującego rerender mapy przy auto-refreshu (mapa duplikowała się pod oryginalną mapą) opisałem to komentarzem TODO.
Dodałem trzy buttony, w tym jeden umożliwiający edycję rozdziału (na razie oczywiście nic nie robi) otwierający modala z formularzem edycji. W formularzu skorzystałem z istniejącego już FormCol, ale był mocno ograniczony więc go zmodyfikowałem żeby działał dla większej liczby przypadków.
Ogólnie zmieniło się bardzo dużo bardzo ważnego kodu, dlatego proszę o bardzo dokładne review i sprawdzenie czy na pewno mapy wyświetlają się poprawnie u studenta i u prowadzącego, i czy w konsoli przeglądarki nie ma errorów ("u mnie działa" ale to dopiero połowa sukcesu ;) )

2022-07-24 18:05 UTC, kwdrt commented
Jako ogólna notka, ale niekoniecznie odnośnie tego commita - RWD na mobilkach się sypie, przynajmniej na Firefoxie:
![firefox_6it8Q5r5zr](https://user-images.githubusercontent.com/56168780/180660120-884f7184-8e40-438c-9904-930d8855e96f.png)
![firefox_NLPBCuQGZs](https://user-images.githubusercontent.com/56168780/180660123-8c001c6f-e040-4785-b35a-44e77fb01ed8.png)
![firefox_vcyWcxhZLI](https://user-images.githubusercontent.com/56168780/180660126-0cc121ce-4df6-4d64-aa9f-710a938e890c.png)

2022-07-24 18:09 UTC, kwdrt commented
Odnośnie tego ekranu - może mniejszy font, przynajmniej na nazwy ekspedycji? Może warunkowo?
![firefox_rtXy4wuZ03](https://user-images.githubusercontent.com/56168780/180660210-2d18e7fb-f385-4af8-ae78-a817ff5cafec.png)

2022-07-24 18:19 UTC, kwdrt commented
GitHub nie daje mi zaznaczyć komentarza w ChaptersNav.js >:(

Odnośnie stackowania map przy refreshu - mówimy o hot reload przy zmianie kodu, czy jakimkolwiek refresh które wywołujemy na stronie z tym elementem który robi problemy?

2022-07-24 18:21 UTC, kwdrt commented
Reszta kodu - oke, przeniesione do innego miejsca to co trzeba, placeholderowe form(iki) są spoko, podoba mi się jak wygląda strona na "normalnych" ekranach. Daj tylko znać pod każdym komentarzem co uważasz, jeśli niektórych rzeczy nie ruszymy (albo nie ruszymy w tym PR, albo nie ruszymy w ogóle bo W w moscoW) to git i zmergujemy.

2022-07-24 18:21 UTC, kwdrt requested changes
Dla formalności, żebyś dostał pinga z GitHuba

2022-07-24 18:21 UTC, kwdrt commented on frontend/src/components/student/GameMapPage/Map/ChapterMap.js
> +      console.log(x, y)
Jest spam w konsoli i ciężko cokolwiek wyczytać (jeśli by było, bo errorów nie spostrzegłem)

Trochę wyżej jeszcze jeden ```console.log()``` do anihilacji

2022-07-25 07:20 UTC, dmncp commented
> Jako ogólna notka, ale niekoniecznie odnośnie tego commita - RWD na mobilkach się sypie, przynajmniej na Firefoxie. Ekran 360 x 800, urządzenie według Firefoxa - Galaxy S20 Linux

Masz na myśli ten navbar czy też np ucina elementy strony znajdujące się na samym dole (przykrywa je sidebarem)?

2022-07-25 07:22 UTC, dmncp commented
> GitHub nie daje mi zaznaczyć komentarza w ChaptersNav.js >:(
> 
> Odnośnie stackowania map przy refreshu - mówimy o hot reload przy zmianie kodu, czy jakimkolwiek refresh które wywołujemy na stronie z tym elementem który robi problemy?

Myślę, że wiesz jaki refresh miałem na myśli, wiele razy tego doświadczyłeś. Chodzi o zachowanie reacta gdy zmienisz coś w kodzie i zapiszesz zmiany (auto refresh zmian na stronie i bum - duplikująca się mapa)

2022-07-25 07:25 UTC, dmncp commented
> Odnośnie tego ekranu - może mniejszy font, przynajmniej na nazwy ekspedycji? Może warunkowo? ![firefox_rtXy4wuZ03](https://user-images.githubusercontent.com/56168780/180660210-2d18e7fb-f385-4af8-ae78-a817ff5cafec.png)

Mogę dać ciut mniejszy font na wszystko, ale to raczej nie zmieni rozjeżdżających się elementów w wierszach. Rozjeżdżają się dlatego, że to nie tabela tylko `ListGroup`, a on nie zachowuje spójności tablarycznej. Mogę to zamienić na tabelę, ale tak bardziej mi się podobało wizualnie. Zamiana na tabelę jest możliwa, trochę byłoby z tym roboty, ale też bez przesady. Daj znać jak wolisz

2022-07-25 07:28 UTC, dmncp commented
> Reszta kodu - oke, przeniesione do innego miejsca to co trzeba, placeholderowe form(iki) są spoko, podoba mi się jak wygląda strona na "normalnych" ekranach. Daj tylko znać pod każdym komentarzem co uważasz, jeśli niektórych rzeczy nie ruszymy (albo nie ruszymy w tym PR, albo nie ruszymy w ogóle bo W w moscoW) to git i zmergujemy.
> 
> Chyba tylko te `console.log()` powiedziałbym że 100% do wywalenia, albo przynajmniej zakomentowania bo to i tak się stanie w kolejnym merge jak ktoś zacznie debugować.

Spróbuję naprawić te widoki żeby były bardziej responsywne. I teraz Ty daj mi znać co myślisz o moich uwagach do Twoich uwag ;). Co do `console.log()`'ów to oczywiście zapomniałem wyrzucić jeżeli są (myślałem, że wyleciały już wszystkie, nic bardziej mylnego jak widać :D )

2022-07-25 16:10 UTC, kwdrt commented
> > GitHub nie daje mi zaznaczyć komentarza w ChaptersNav.js >:(
> > Odnośnie stackowania map przy refreshu - mówimy o hot reload przy zmianie kodu, czy jakimkolwiek refresh które wywołujemy na stronie z tym elementem który robi problemy?
> 
> Myślę, że wiesz jaki refresh miałem na myśli, wiele razy tego doświadczyłeś. Chodzi o zachowanie reacta gdy zmienisz coś w kodzie i zapiszesz zmiany (auto refresh zmian na stronie i bum - duplikująca się mapa)

Wydaje mi się że to nie jest wielki problem, bo hot reload powoduje przeładowanie strony z jakiegoś powodu i chyba po prostu zostają "śmieci" z pamięci kiedy zmieni się develop, ale można rzucić okiem kiedyś, tbh low priority

2022-07-25 16:11 UTC, kwdrt approved these changes
Dobrze zrobione, to co miało być naprawione teraz jest więc daję approve

2022-07-25 16:17 UTC, merged