[SC-116] Zamiana mocków na dane z bazy w liście aktywności do sprawdzenia
ajablonsk1/systematic-chaos pull request #89
Opened 2022-07-30 12:53 UTC by kwdrt

Podmienione mocki na właściwe wartości pobierane z API - back zwraca nam tylko id i ile do oceny (dawne API miało id unikalne w skali całej bazy, a nie rodzaju aktywności) więc obecnie to, co trzeba jest hardcoded na fileTaski - według naszego obecnego zamysłu nie ma powodu żebyśmy oceniali cokolwiek co nie jest fileTaskiem, a muszę wyciągnąć dane na temat aktywności do podsumowania.

<img src="https://user-images.githubusercontent.com/56168780/181915135-748093e8-5357-4d57-9126-d91ea04c257d.png" width=400

2022-07-30 15:58 UTC, dmncp requested changes

2022-07-30 15:58 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +import { useEffect, useState } from 'react'
Pierdoła i piszę jako ciekawostkę - zgodnie z konwencją import z 'react' ma być zawsze w linii 1

2022-07-30 15:58 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +          activityList.map((element) => {
skoro activityList to bardziej pasuje 
```js
activityList.map((activity) => ...)
```

2022-07-30 15:58 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +            return ExpeditionService.getExpedition(element.activityId).then((response) => {
Dlaczego `ExpeditionService` ? To nie jest tak, że ekspedycje mają tylko pytania, które się same sprawdzają ? Nie powinno być raczej 
```js
CombatTaskService.getCombatTask(element.activityId) ...
```
?

2022-07-30 15:58 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +  const [activityList, setActivityList] = useState('')
Nie wiem czy to dobry pomysł, żeby wartość domyślna to był pusty string. Ja bym raczej dał undefined

2022-07-30 15:58 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +      })
To wszystko jest do korekty, bo skorzystałeś ze złego endpointa, tak jak napisałem w komentarzu wyżej. Wtedy nieco się zmieni cały ten useEffect

2022-07-30 15:58 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +      })
Moim zdaniem bez sensu rzucać error bo on nie zostanie już nigdzie wyżej przekazany. To jest moment na złapanie errora rzuconego z niższego poziomu i wykorzystanie faktu że jest error, tzn tak jak ja robiłem w error handlingu:
```js
.catch(() => {
    setActivityList(null) // z racji że ustawimy null, a domyślnie będzie undefined to możemy rozróżnić czy jest błąd czy "pending"
})

2022-07-30 15:58 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +          })}
Trzeba obsłużyć poprawnie errora teraz. Tzn
```js
{activityList === undefined ? <Loader/> : activityList == null ? <p>{ERROR_OCCURED}</p>} : activityList.map ...
```

2022-07-30 15:58 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityListItem.js
> +
do wyrzucenia

2022-07-30 15:58 UTC, dmncp commented on frontend/src/services/professor.service.js
>  }
dodaj 
```js
.catch((error) => {
    throw error
}

2022-07-30 16:00 UTC, dmncp commented
> Podmienione mocki na właściwe wartości pobierane z API - back zwraca nam tylko id i ile do oceny (dawne API miało id unikalne w skali całej bazy, a nie rodzaju aktywności) więc obecnie to, co trzeba jest hardcoded na fileTaski - według naszego obecnego zamysłu nie ma powodu żebyśmy oceniali cokolwiek co nie jest fileTaskiem, a muszę wyciągnąć dane na temat aktywności do podsumowania.
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/56168780/181915135-748093e8-5357-4d57-9126-d91ea04c257d.png">

opis się zgadza ale użyłeś ekspedycji a nie file taska

2022-07-30 16:01 UTC, dmncp commented
Próbowałeś też w tym tasku ogarnąć zamianę mocków na dane właściwe na stronie do której przechodzisz klikając w odpowiedni wiersz w tym widoku ? Czy to już na kolejnego taska ?

2022-07-30 16:03 UTC, dmncp requested changes

2022-07-30 16:03 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +            console.log(toGrade)
do wyrzucenia

2022-07-30 16:35 UTC, kwdrt commented
> Próbowałeś też w tym tasku ogarnąć zamianę mocków na dane właściwe na stronie do której przechodzisz klikając w odpowiedni wiersz w tym widoku ? Czy to już na kolejnego taska ?

To jest kolejny task - pobieranie konkretnych tasków do sprawdzenia na razie stoi przez wymagany mail na pobieraniu odpowiedzi, back nie ma też na razie opcji (jeśli czegoś nie przeoczyłem) żeby oznaczyć pytanie jako "sprawdzone", czyli pierwsze z brzegu do sprawdzenia będzie to samo - ale JIRA ma task na sprawdzanie jeszcze niewykonany, więc może po prostu tego jeszcze nie ma.

Flow przechodzenia po odpowiedziach zakładam jako:
- pobierz pierwsze pytanie
- sprawdź, udziel uwag, daj punkty itp.
- po kliknięciu że sprawdzone przejdź do kolejnego i zaktualizuj dane na stronie

aż nie skończą się pytania do sprawdzenia

2022-07-30 16:38 UTC, kwdrt commented
Sprawdziłem - to chyba scope SC-95 którego jeszcze nie mamy. Ale jeśli wyjdzie że długo jeszcze tego nie będzie, to po prostu rozbiję na 2 taski i wepnę na razie to co pobiera z pierwszej odpowiedzi i wyświetlę te dane jako pierwsze, bez całej nawigacji "sprawdzającej"

Z tego co widzę np. nie jest doczepiony mail w task/evaluate/first, ani żaden identyfikator usera więc nie da rady na razie ogarnąć nawet tego, czyli to dalej byłby tak na 60% mock

2022-07-30 16:40 UTC, dmncp commented
> > Próbowałeś też w tym tasku ogarnąć zamianę mocków na dane właściwe na stronie do której przechodzisz klikając w odpowiedni wiersz w tym widoku ? Czy to już na kolejnego taska ?
> 
> To jest kolejny task - pobieranie konkretnych tasków do sprawdzenia na razie stoi przez wymagany mail na pobieraniu odpowiedzi, back nie ma też na razie opcji (jeśli czegoś nie przeoczyłem) żeby oznaczyć pytanie jako "sprawdzone", czyli pierwsze z brzegu do sprawdzenia będzie to samo - ale JIRA ma task na sprawdzanie jeszcze niewykonany, więc może po prostu tego jeszcze nie ma.
> 
> Flow przechodzenia po odpowiedziach zakładam jako:
> 
> * pobierz pierwsze pytanie
> * sprawdź, udziel uwag, daj punkty itp.
> * po kliknięciu że sprawdzone przejdź do kolejnego i zaktualizuj dane na stronie
> 
> aż nie skończą się pytania do sprawdzenia

Okej, kumam :D 
Też tak widzę to flow

2022-07-30 17:02 UTC, dmncp requested changes

2022-07-30 17:02 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +// note: currently the list assumes we only can only manually grade File Tasks - this is due to the way our DB currently works,
... we only can manually ...

2022-07-30 17:02 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +// an ID is unique only in the task group. we might need to add task type differentation on the backend if we want to check
differentiation?

2022-07-30 17:02 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +  }, [])
To Ci dalej nie zadziała, wysypie się przy zwykłym 404 z getCombatTaskProfessor. Jeżeli chcesz to zostawić w takiej postaci musisz dać w linii 30:
```js
setActivityList(
    response[0].status === 'rejected'
        ? null
        : response?.map((activity) => {
            return {
                activity: activity.value
            }
          })
)
```

2022-07-30 17:02 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +          <p>{ERROR_OCCURED}</p>
```suggestion
          <p className={'text-center text-danger h4'}>{ERROR_OCCURED}</p>
```

2022-07-30 17:02 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +          activityList.map((activity) => {
activityList?.map

2022-07-30 17:02 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +            response.map((activity) => {
response?.map((activity)

2022-07-30 17:04 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +  }, [])
chciałem dla testu dać catcha ale okazuje się że błędy też wchodzą do then ale ze statusem "rejected"

2022-07-30 17:07 UTC, dmncp requested changes

2022-07-30 17:07 UTC, dmncp commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +      .catch(() => {
Wyrzuć tą pustą linię

2022-07-30 17:11 UTC, kwdrt commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +  }, [])
Tzn? Nawet po poprawionym kodzie?

2022-07-30 17:12 UTC, kwdrt commented on frontend/src/components/professor/ActivityAssessmentList/ActivityAssessmentList.js
> +  }, [])
Wydaje mi się że allSettled obsługuje błędy w sobie, więc chyba nie ma problemów

2022-07-31 09:14 UTC, dmncp approved these changes

2022-07-31 09:15 UTC, merged